### ISSUE TITLE
Fails to start registering the Google Play Service

### ISSUE THREAD

**Issue by EelcoA** [janbar/noson-app#10]
First big thanks for this very nice Sonos App, I'm enjoying it. Made me upgrade from 14.04 to 16.04 ;-)

I try to register my Google Play service, but pressing the green button gives no response. 7Digital and TuneIn worked direct. Soundcloud works as well after registration. 

Any suggestions?

kind regards,
Eelco

**Comment by ghostal** [comment]
Thanks also!

I am having the same problem with Google Play Music - clicking the "Start service registration" button shows the loading spinner for a short moment, but then it disappears and nothing happens.

Service registration for Spotify, for example, works fine though.

**Comment by EelcoA** [comment]
I noticed that, although registration failed, Google Play does function. I have a Google Music link added to my favorites and it works! So registration is working, or not necessary.

**Comment by ghostal** [comment]
@EelcoA Are you able to search and browse through Google Play Music?

**Comment by EelcoA** [comment]
@ghostal Nope, I can only play albums or lists from Google PLay that I've added to my Favorites, no browsing.

**Comment by janbar** [comment]
Hi, There is an issue in the protocol with Google. The sonos api documentation available from web seems to be obsolete. Once I have more info, I will patch the app.

**Comment by janbar** [comment]
I fixed a xml hearder for smapi. Could someone check the new version 2.4.0 for Google service registration issue. Thanks.

**Comment by EelcoA** [comment]
I just installed noson-app_2.4 through, but Google Play is still not working. 7Digital, Soundcloud work fine. Google Play still has the same issue. And this is weird, because the entry for the random mix for google play in my Favorites does work. So I can play songs, but can not browse them.

BTW, I could only see that I got version 2.4.0. through the update log. I could not find it anywhere in the app (screen of files) itself. Would be nice to be able to check that I am indeed running the right version.

Anyhow, thanks for trying, and I do enjoy the app a lot, keep up the good work!

**Comment by pascalopitz** [comment]
What user agent string are you guys using? I recently found out Google Play's pretty fickle. Soco provided the answer: https://github.com/SoCo/SoCo/blob/18ee1ec11bba8463c4536aa7c2a25f5c20a051a4/soco/music_services/music_service.py#L55

**Comment by janbar** [comment]
@pascalopitz many thanks for the clear steer. I use the user agent `libnoson/1.0`. Seems it should be the root cause of the issue. I will fix as soon as possible.

**Comment by pascalopitz** [comment]
No worries. I had the same issue.

**Comment by janbar** [comment]
In fact, I used the agent string from sonos device itself: `Linux UPnP/1.0 Sonos/36.4-42130 (ZP90)`.
Removing the device model it works now !

**Comment by janbar** [comment]
And more pending authorization, the fault code returned by Google api doesn't match with the protocol specifications of the Sonos API. The fault code returned is `soap:server` instead `NOT_LINKED_RETRY`.

**Comment by janbar** [comment]
I pushed the update. The build is running now for PPA packages and SNAP package using last release 2.4.2.
You can check the version of the noson core library at url `http://localhost:1400/` after launching the app. The latest version of the core library fixing this issue is 1.4.2. The app version is 2.4.2.

**Comment by janbar** [comment]
@EelcoA , please let me now if you solved the issue with the latest version. Thanks for your help.

**Comment by EelcoA** [comment]
@janbar I received the new version, new broker 1.4.2, but don't know app version, how can I check that? 

Anyhow, we're one step further :-) But not there yet.  Clicking on the button to start the registration gives me a url: https://www.google.com/device. With that url I have to log into Google, pick the desired google account, and then it asks for a code that should be shown on the device. Apparently now Noson has to show a number, but doesn't.

See attached screenprint (in dutch)

![schermafdruk van 2017-07-20 09-37-00](https://user-images.githubusercontent.com/9035993/28406265-18debf86-6d30-11e7-9af0-58676ddd3775.png)

**Comment by pascalopitz** [comment]
AppLink and DeviceLink responses contain `linkCode` and `showLinkCode`. If the latter is true, the former is to be displayed to the user.

**Comment by janbar** [comment]
I missed those stuff...
My new update in version 2.4.3 shows screens below:

![capture du 2017-07-20 13-45-06](https://user-images.githubusercontent.com/2353635/28415984-671955ae-6d52-11e7-8855-610ce5ac4de6.png)
![capture du 2017-07-20 13-45-25](https://user-images.githubusercontent.com/2353635/28415987-69aa728a-6d52-11e7-8465-1705cc687d5e.png)

Hope it will help !

**Comment by EelcoA** [comment]
I do get in now, although, it looks like that. Authorisation is granted, but all is empty, no albums, no artists, no songs. All empty ;-(  Only the playlists are shown, but also empty.

**Comment by janbar** [comment]
Are containers (folder Albums,Artists...) show ? And they are empty...

**Comment by EelcoA** [comment]
First time they were shown, and Playlist showed my playlists, only they were empty. Now (I had to restart my computer) the containers are not shown. 

BTW, You can sign up for Google Play for free and upload some albums, no need to pay. It is how I use it, as a cloud backup for my music. Just in case you didn't know.

![afbeelding](https://user-images.githubusercontent.com/9035993/28479473-e12f960e-6e5c-11e7-8494-08af1846b427.png)

**Comment by janbar** [comment]
I didn't know ! Now I am trying a free account for the Google play service. I will let you know what I can do.

**Comment by janbar** [comment]
That works now, and it allows me to fix a bug in my shared code. Thanks for your contribution.

**Comment by janbar** [comment]
Fix version is : 2.4.4 (core lib 1.5.1)

**Comment by EelcoA** [comment]
Yes, it works! Had to remove the .cache folder, but after that, like a charm :-) Thanks. And you're not the first one I tell about the awesome free cloud option of Google Play. Enjoy, glad I could help.

**Comment by EelcoA** [comment]
@janbar unfortunately, the Google Play Musice service does not work any more. It still says 'Google Play Eelco', but clicking on it fails to show anything. Not even the containers. 7Digital and Soundcloud work. Any way I can remove all settings to start it all over again?

**Comment by janbar** [comment]
Mmm. Probably the token refreshing fails. This service is fussy. I will test it this evening with my account.

**Comment by janbar** [comment]
@EelcoA , here it works. The token is refreshed normally (at every new instance of the service). Running noson-app with option --debug you should see something like that when entering in the service first time:
```
(SONOS)Connect: SSL handshake initialized
(SONOS)Connect: /C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.googleapis.com
(SONOS)SendRequest: POST /music/sonos/wsf/smapi HTTP/1.1
Host: mclients.googleapis.com:443
User-Agent: Linux UPnP/1.0 Sonos/26.99-12345
Connection: close
Accept-Charset: utf-8
Content-Type: text/xml; charset=utf-8
Content-Length: 751
Accept-Encoding: gzip, deflate
Accept-Language: fr_FR, en-US;q=0.9
SOAPAction: "http://www.sonos.com/Services/1.1#getMetadata"

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Header><credentials xmlns="http://www.sonos.com/Services/1.1"><deviceId>XXXXXXXXX:0</deviceId><deviceProvider>Sonos</deviceProvider><loginToken><token>HHID_XXXXXXXXXX</token><key>XXXXXXXXXXXXXXXX</key><householdId>HHID_XXXXXXXXXXXXXX</householdId></loginToken></credentials></s:Header><s:Body><ns:getMetadata xmlns:ns="http://www.sonos.com/Services/1.1"><ns:id>root</ns:id><ns:index>0</ns:index><ns:count>100</ns:count><ns:recursive>false</ns:recursive></ns:getMetadata></s:Body></s:Envelope>
(SONOS)GetResponse: HTTP/1.1 500 Internal Server Error
(SONOS)GetResponse: Content-Type: text/xml; charset=UTF-8
(SONOS)GetResponse: Content-Encoding: gzip
(SONOS)GetResponse: Date: Mon, 24 Jul 2017 18:53:20 GMT
(SONOS)GetResponse: Expires: Mon, 24 Jul 2017 18:53:20 GMT
(SONOS)GetResponse: Cache-Control: private, max-age=0
(SONOS)GetResponse: X-Content-Type-Options: nosniff
(SONOS)GetResponse: X-Frame-Options: SAMEORIGIN
(SONOS)GetResponse: X-XSS-Protection: 1; mode=block
(SONOS)GetResponse: Server: GSE
(SONOS)GetResponse: Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
(SONOS)GetResponse: Connection: close
(SONOS)GetResponse: Transfer-Encoding: chunked
(SONOS)GetResponse: 
(SONOS)WSResponse: server error (500)
(SONOS)ReadChunk: chunked data (00000001)
(SONOS)ReadChunk: chunked data (00000001)
(SONOS)ReadChunk: chunked data (00174)
(SONOS)DoCall: [fault] authToken = XXXXXXXXXXXXXXXXXXX
(SONOS)DoCall: [fault] privateKey = XXXXXXXXXXXXXXXXXXX
(SONOS)SetFault: TAG (Fault)
(SONOS)SetFault: faultcode (soap:Client.TokenRefreshRequired)
(SONOS)SetFault: faultstring (Client.TokenRefreshRequired)
(SONOS)SetFault: authToken (XXXXXXXXXXXXXXXXXXXXXXXX)
(SONOS)SetFault: privateKey (XXXXXXXXXXXXXXXXXXXXXXXX)
(SONOS)Connect: SSL handshake initialized
(SONOS)Connect: /C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.googleapis.com
(SONOS)SendRequest: POST /music/sonos/wsf/smapi HTTP/1.1
Host: mclients.googleapis.com:443
User-Agent: Linux UPnP/1.0 Sonos/26.99-12345
Connection: close
Accept-Charset: utf-8
Content-Type: text/xml; charset=utf-8
Content-Length: 850
Accept-Encoding: gzip, deflate
Accept-Language: fr_FR, en-US;q=0.9
SOAPAction: "http://www.sonos.com/Services/1.1#getMetadata"

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Header><credentials xmlns="http://www.sonos.com/Services/1.1"><deviceId>XXXXXX:0</deviceId><deviceProvider>Sonos</deviceProvider><loginToken><token>XXXXXXXXXXXXXXXXX</token><key>XXXXXXXXXXXXXXXXXXXXXX</key><householdId>HHID_XXXXXXXXXX</householdId></loginToken></credentials></s:Header><s:Body><ns:getMetadata xmlns:ns="http://www.sonos.com/Services/1.1"><ns:id>root</ns:id><ns:index>0</ns:index><ns:count>100</ns:count><ns:recursive>false</ns:recursive></ns:getMetadata></s:Body></s:Envelope>
(SONOS)GetResponse: HTTP/1.1 200 OK
(SONOS)GetResponse: Content-Type: text/xml; charset=UTF-8
(SONOS)GetResponse: Content-Encoding: gzip
(SONOS)GetResponse: Date: Mon, 24 Jul 2017 18:53:21 GMT
(SONOS)GetResponse: Expires: Mon, 24 Jul 2017 18:53:21 GMT
(SONOS)GetResponse: Cache-Control: private, max-age=0
(SONOS)GetResponse: X-Content-Type-Options: nosniff
(SONOS)GetResponse: X-Frame-Options: SAMEORIGIN
(SONOS)GetResponse: X-XSS-Protection: 1; mode=block
(SONOS)GetResponse: Server: GSE
(SONOS)GetResponse: Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
(SONOS)GetResponse: Connection: close
(SONOS)GetResponse: Transfer-Encoding: chunked
(SONOS)GetResponse: 
(SONOS)ReadChunk: chunked data (00000001)
(SONOS)ReadChunk: chunked data (00000001)
(SONOS)ReadChunk: chunked data (00000001)
(SONOS)ReadChunk: chunked data (00000001)
(SONOS)ReadChunk: chunked data (01)
(SONOS)ReadChunk: chunked data (19e)
(SONOS)DoCall: dump (getMetadataResult)
<getMetadataResult>
    <index>0</index>
    <count>2</count>
    <total>2</total>
    <mediaCollection>
        <id>pxIasSYsGYc</id>
        <itemType>program</itemType>
        <title>Mix "J'ai de la chance"</title>
        <canPlay>true</canPlay>
        <canEnumerate>true</canEnumerate>
        <albumArtURI>https://www.gstatic.com/play/music/sonosfe/XXXXXX/images/orange/ifl_icon_72.png</albumArtURI>
    </mediaCollection>
    <mediaCollection>
        <id>uNSX3oy6his</id>
        <itemType>favorites</itemType>
        <title>Bibliothèque musicale</title>
        <albumArtURI>https://www.gstatic.com/play/music/sonosfe/XXXXXX/images/orange/mylibrary_icon_72.png</albumArtURI>
    </mediaCollection>
</getMetadataResult>

(SONOS)GetItems: [0] mediaCollection (program)(pxIasSYsGYc)
(SONOS)MakeUriMetadata: sid 151 (000c206cpxIasSYsGYc)(0)
(SONOS)GetItems: [1] mediaCollection (favorites)(uNSX3oy6his)
```

**Comment by janbar** [comment]
You can run the app with flag --debug and save the log into file with the following command:

```noson-app --debug 2>&1 | tee noson.log```

**Do not paste the file here because it contains credentials.**

**Comment by EelcoA** [comment]
@janbar So I did, and now? what to look for. A bit too much data for me to go through. ;-)

Although I see one weird thing already, that it gets errors trying to retrieve images from an old ip address that used to contain my music. But since all is working well on SONOS with the new NAS address, that is a bit weird.

But that has nothing to do with the Google Play service (or at least shouldn't). Can I send you the log file?

**Comment by janbar** [comment]
Yes, you can send the log file to my email address: jlbarriere68@gmail.com

**Comment by janbar** [comment]
@EelcoA , please could you request with a web browser the url:

`http://192.168.1.120:1400/status/accounts`

Then check if you have a value for the field `OADevID` for the account Google. Seems the App didn't extract the required value.

**Comment by janbar** [comment]
![capture du 2017-07-25 20-23-21](https://user-images.githubusercontent.com/2353635/28587343-27520f64-7177-11e7-8d81-7ffbf1facea7.png)

**Comment by EelcoA** [comment]
The request delivers nothing, not in the browser, not with wget

**Comment by janbar** [comment]
No problem, it seems that could depend of the sonos device and firmware version. I saw the issue in your debug log for the google account. Your sonos device no longer provides a value for field "OADevID" in the accounts request response. I will make an update soon to default the value with the "householdID" of the device. Then that should work again.

**Comment by janbar** [comment]
Finishing the fix, the Google service no longer work here now ! They probably changed something in their api today that break the client with error: "Unable to authorize Google Play Music. Please contact Sonos Customer Care."

**Comment by janbar** [comment]
@pascalopitz have you a failure too with Google service since few hours ?

**Comment by pascalopitz** [comment]
Yes, indeed :(

**Comment by EelcoA** [comment]
And maybe it is part of the problem, but it seems that Noson does not remember the credentials for 7Digital and Soundcloud. Every time I have to go through the registration process again.

**Comment by EelcoA** [comment]
Just installed new version of Noson (Event Broker Version 1.5.4, compiled on Jul 27 2017 at 12:18:33 ) and removed the .config/noson.janbar/noson.janbar.conf.

Registered for 
- 7Digital: worked, 
- Registered for Soundcloud: worked, but I have to do it again after restarting Noson
- Registering Google Play: failed, nothing happens when pressing the "Start Registration" button, no link, no browser-new-page.

**Comment by janbar** [comment]
Thanks for feedback. Since few weeks ago some services using "userId" registration, they expire the session after one day or few hours (i.e 7Digital). Because Noson doesn't store your password , you have to enter it again after expiration. I am pushing now an update with the version 2.4.7 (1.5.5), to fill the "username" because it can be retrieved from Sonos device. So you will have to enter only your password to re-enable the service session.
About Google service, seems that's broken for now, caused by their API update occurred yesterday.

**Comment by EelcoA** [comment]
@janbar Thanks for the update. Username was shown for 7digital, so only had to enter the password. You don't want Noson to store the passwords (encrypted)? Would be nice. For Soundcloud I had to register again as well. How does Sonos do that then? There I never have to re-register?

**Comment by janbar** [comment]
Sonos stores your password, also its sources aren t open like noson.

**Comment by janbar** [comment]
Weird Soundcloud expires your session as soon ! Maybe the session id failed to be stored on noson config.

**Comment by janbar** [comment]
@EelcoA , so finally I reviewed my opinion and the version 2.4.8 (1.5.5) will store password into account settings to allow auto registration. So once the current session becomes expired the app will request one time the password and keep it into settings to enable automatic session refreshing. That's work here with 7Digital, and Deezer.

**Comment by EelcoA** [comment]
@janbar 7Digital and Soundcloud work and keep working, thanks!

**Comment by luisgjb** [comment]
i have the same problem with Apple music.. in the log the only thing that i think is important is this :
`(SONOS)__dumpInvalidResponse: invalid or not supported response
(SONOS)<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <SOAP-ENV:Fault>
            <faultcode>SOAP-ENV:Server</faultcode>
            <faultstring xml:lang="en">There was an error processing your request</faultstring>
            <detail>
                <customFaultDetail xmlns="http://www.sonos.com/Services/1.1">
                    <SonosError>999</SonosError>
                </customFaultDetail>
                <bonus/>
            </detail>
        </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

(SONOS)GetAppLink: parse xml failed
`

**Comment by luisgjb** [comment]
i have the same problem with Apple music.. in the log the only thing that i think is important is this :
`
(SONOS)__dumpInvalidResponse: invalid or not supported response
(SONOS)<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
SOAP-ENV:Header/
SOAP-ENV:Body
SOAP-ENV:Fault
SOAP-ENV:Server
There was an error processing your request
999
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
(SONOS)GetAppLink: parse xml failed
`

**Comment by davparker** [comment]
Just installed this on Ubuntu Desktop 18.04. I had to register Pandora 3 tries before it took. The web registration succeeded, but the Noson app kept saying I needed to register again. But, third time was the charm.   With Google Play, the web registration link never opens. But, cool, I mostly use Pandora anyway.
Thanks!

**Comment by benhbell** [comment]
Running into this issue with the latest noson on ubuntu 18.04 as well.

**Comment by geblix3000** [comment]
At first...great work! 

But same problem, with Apple Music. Using Manjaro with all latest packages and installes your app via Snap Packages. 


`(SONOS)WSResponse: server error (500)
(SONOS)__dumpInvalidResponse: invalid or not supported response
(SONOS)<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <SOAP-ENV:Fault>
            <faultcode>SOAP-ENV:Server</faultcode>
            <faultstring xml:lang="en">There was an error processing your request</faultstring>
            <detail>
                <customFaultDetail xmlns="http://www.sonos.com/Services/1.1">
                    <SonosError>999</SonosError>
                </customFaultDetail>
                <bonus/>
            </detail>
        </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

(SONOS)GetAppLink: parse xml failed
`

**Comment by Zabari** [comment]
Same problem with Google Play :(
any leads?

**Comment by larsvinder** [comment]
No updates on the Google Play problem?

**Comment by janbar** [comment]
There are secret tricks to make it work. If someone gives me the Sonos or Google sources, I can fix it. But do not dream, these sources are closed.
Deezer, Spotify and many others work great, so ...

**Comment by Fabi0Z** [comment]
Arch Linux, build from git master, the service registration button doesn't give me the registration link, here's the log via terminal

`(SONOS)WSResponse: server error (500)
(SONOS)GetDeviceLinkCode: parse xml failed`

**Comment by r7xf** [comment]
> Arch Linux, build from git master, the service registration button doesn't give me the registration link, here's the log via terminal
> 
> `(SONOS)WSResponse: server error (500)`
> `(SONOS)GetDeviceLinkCode: parse xml failed`

I can confirm, same happens with a fresh build on Debian.

**Comment by janbar** [comment]
@r7xf , for now I have no way to retrieve the origin of this failure. Before I used a memory dump of the Sonos app on windows to fish the right call., but that is a heavy task. For Google I think the error could be in the http headers..  Maybe they expect something special.

**Comment by sebvallee** [comment]
I bump this, because I'm in the same case ! I just got some logs (more detailled and complete), maybe this will help to debug this ! My config is Archlinux, but build from AUR, which build from source on git.
[debug.noson.log](https://github.com/janbar/noson-app/files/3873833/debug.noson.log)
You can see the problem on line 672, the app got a 500 http response from sonos.com webserver.
Many thanks for any help on this !

**Comment by hailwood** [comment]
Another bump. No Google services are working here :(

**Comment by ilvenini** [comment]
It's not working for me either

**Comment by sfllaw** [comment]
@svrooij seems to have discovered a way to authenticate?
https://github.com/SoCo/SoCo/issues/586#issuecomment-728229811:
> @KennethNielsen I've [documented](https://svrooij.io/sonos-api-docs/music-services.html) how to connect to external music services.
> 
> anyone who wants me to continue this research, please [sponsor me](https://github.com/sponsors/svrooij?o=esc)
> 
> This file shows how to login to any music service [trigger login to music service](https://github.com/svrooij/node-sonos-ts/blob/beta/examples/music-services-login.js)
> 
> And this file shows how to browse any logged-in music service [browse](https://github.com/svrooij/node-sonos-ts/blob/beta/examples/music-services.js), I’ve tested Spotify and several others which are register for free.
> 
> The first link in this message shows what request to do, and the last two links show an actual working app querying music services. This information show be enough to replicate the same in python. Hope it helps... I also tried documenting the local Sonos api [here](https://svrooij.io/sonos-api-docs/services/) so if you want you can also use my work on that part to make SoCo even better.

**Comment by svrooij** [comment]
@sfllaw you are right.

I've build a working login and browse client for all music clients. See https://github.com/svrooij/node-sonos-ts/blob/master/examples/music-services-login.js

And I documented the entire local Sonos API here https://svrooij.io/sonos-api-docs/

I won't build a python version, but it should give some good pointers. If you guys need help, the above offer still stands. If I have enough sponsors I'm able to spend some more time on it.

**Comment by svrooij** [comment]
> Have you been able to authenticate with Apple Music service?

@goldyfruit I'm no Apple user, but it should be similar. As long as they don't require device certificates for browsing.

Do you get an error message or you just haven't tried it yet?

**Comment by goldyfruit** [comment]
> > Have you been able to authenticate with Apple Music service?
> 
> @goldyfruit I'm no Apple user, but it should be similar. As long as they don't require device certificates for browsing.
> 
> Do you get an error message or you just haven't tried it yet?
Yep, I had to change the XML payload to add some fields:
```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.sonos.com/Services/1.1">
   <s:Header>
      <credentials xmlns="http://www.sonos.com/Services/1.1">
         <deviceId>XXXXX</deviceId>
         <deviceProvider>Sonos</deviceProvider>
      </credentials>
   </s:Header>
   <s:Body>
      <getAppLink xmlns="http://www.sonos.com/Services/1.1">
         <householdId>XXX</householdId>
         <hardware>Sonos</hardware>
         <osVersion>S2</osVersion>
         <sonosAppName>ACR_Nexus7,2</sonosAppName>
         <callbackPath></callbackPath>   
      </getAppLink>
   </s:Body>
</s:Envelope>
```
The response is:

```xml
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns2:getAppLinkResponse xmlns:ns2="http://www.sonos.com/Services/1.1">
            <ns2:getAppLinkResult>
                <ns2:authorizeAccount>
                    <ns2:appUrl>music://itunes.apple.com/sonosAuth?callbackUrl=&amp;householdId=XXXXXX&amp;ct=signin&amp;at=1001l9kG&amp;action=login&amp;encryptedHouseholdId=</ns2:appUrl>
                    <ns2:appUrlStringId>LoginAppleMusic</ns2:appUrlStringId>
                    <ns2:failureStringId>AuthorizeFailure</ns2:failureStringId>
                    <ns2:failureUrl>sonos.com</ns2:failureUrl>
                </ns2:authorizeAccount>
                <ns2:createAccount>
                    <ns2:appUrl>music://itunes.apple.com/sonosAuth?callbackUrl=&amp;householdId=XXXXXX&amp;ct=start_trial&amp;at=1001l9kG&amp;action=signup&amp;encryptedHouseholdId=</ns2:appUrl>
                    <ns2:appUrlStringId>StartTrial</ns2:appUrlStringId>
                    <ns2:failureStringId>AuthorizeFailure</ns2:failureStringId>
                    <ns2:failureUrl>sonos.com</ns2:failureUrl>
                </ns2:createAccount>
                <ns2:installAction>
                    <ns2:messageStringId>AndroidInstallMessage</ns2:messageStringId>
                    <ns2:url>market://details?id=com.apple.android.music</ns2:url>
                    <ns2:urlStringId>AndroidInstall</ns2:urlStringId>
                </ns2:installAction>
                <ns2:appUrlEncrypt>true</ns2:appUrlEncrypt>
            </ns2:getAppLinkResult>
        </ns2:getAppLinkResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
There is no `regUrl` which I guess is because I don't have the right payload.
